const GlobalActionTypes = {
  SHOW_LOADING: "SHOW_LOADING", 
  HIDE_LOADING: "HIDE_LOADING",
  SHOW_LOADING_BUTTON: "SHOW_LOADING_BUTTON",
  HIDE_LOADING_BUTTON: "HIDE_LOADING_BUTTON",
};

export default GlobalActionTypes;
